<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.2/tailwind.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
    <title>Retailer</title>
</head>
<body>
    <!--
        - Add item, quantity, price
        - Edit or remove items added
        - Send items via POST
        - redirect to session page 
    -->
    <div id="app">
        <div class="top-bar">
            <input type="text" name="new-item-name" id="new-item-name" v-model="gName" value="Placeholder">
            <input type="number" name="new-item-q" id="new-item-q" v-model="gQ" max="99" min="1" value="1">
            <input type="number" name="item-price" id="item-price" v-model="gPrice" max="10000.0" min="0.0" step = "0.01" value="10.00">
            <button class="add" v-on:click="addItem">
                Add item
            </button>

        </div>
        <div class="item-list">
            <item v-for="item in items" :name="" class="item"></item>
        </div>
    </div>
    <script src="merchant.js"></script>
</body>
</html>